export const COUNTER_INCREMENT = 'COUNTER_INCREMENT'
export const COUNTER_DECREASE = 'COUNTER_DECREASE'

export const OPEN_CONFIRM_DIALOG = 'OPEN_CONFIRM_DIALOG'
export const CLOSE_CONFIRM_DIALOG = 'CLOSE_CONFIRM_DIALOG'

export const LOCATION_CHANGE = '@@router/LOCATION_CHANGE'

export const ROTATE_LOADING_CIRCLE = 'ROTATE_LOADING_CIRCLE'
export const STOP_LOADING_CIRCLE = 'STOP_LOADING_CIRCLE'
